### ISSUE TITLE
Check possibility of using github-actions-version of reviewdog

### ISSUE THREAD

**Issue by taraskozub-percona** [percona/pmm#1239]
### Description

Currently we're using local version of **reviewdog** in our CI. There is a github-actions-version https://github.com/reviewdog/action-golangci-lint. The problem of using actions-version is that we're using **golangci-lint** for local tests. In case we use two different types of **golangci-lint** (locally built one for local tests and the other one for actions-version of reviewdog) we need to sync versions of **golangci-lint** to be sure we're using the same version of linter. We can consider to use just the latest version of **golangci-lint** if we can configure our CI such a way.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Azanul** [comment]
This is very much possible by using [review dog config file](https://github.com/reviewdog/reviewdog#reviewdog-config-file).
I'd like to work on this.

**Comment by artemgavrilov** [comment]
@Azanul Hi, I'm not sure how reviewdog config file will help here. We have two ways to run linters:

1. invoke `make check` target in the project root (we use it local environments)
2. In CI where we invoke golangci-lint and route it's output to the reviewdog

So it seems that for CI we can just use official GH Action. But in that case we somehow should sync golangci-lint version that we use for local run (1) and in CI (2).

Let's do the following, for now let's just replace that part that we [use for CI ](https://github.com/percona/pmm/blob/0c3b4da14e90b4461712403398b03cf86a45b29c/.github/workflows/common.yml#L83-L98) with this [GH action](https://github.com/reviewdog/action-golangci-lint)

**Comment by Azanul** [comment]
@artemgavrilov Sorry I misinterpreted the issue, now I get it.
The only golangci version issue I see is in [this line](https://github.com/percona/pmm/blob/0c3b4da14e90b4461712403398b03cf86a45b29c/Makefile.include#L22).

We can fix that by replacing it with these two lines:
```
LATEST_GOLANGCI_LINT_VERSION=$(curl -sL https://api.github.com/repos/golangci/golangci-lint/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin $LATEST_GOLANGCI_LINT_VERSION
```

In addition to what you mentioned, replacing binary build of golangci-lint with the action.
What do you think?

**Comment by artemgavrilov** [comment]
@Azanul  Golnagci-lint [docs ](https://golangci-lint.run/usage/install/#other-ci)recommend  always use specific version. We want always have reproducible builds, so better to have pinned version everywhere. 

Let's keep local golangci-lint installation as is, but for CI lets use Action with the same version.
