### ISSUE TITLE
PMM agent postgresql high cpu usage

### ISSUE THREAD

**Issue by neverlless** [percona/pmm#1258]
### Description

I have a 14.3 postgres server that contains about 900+ databases.

With standard server operation, I have a CPU load of no more than 10%.

When running PMM agent on the same server to monitor postgres, 10 minutes later my server has 100% CPU usage.

After analyzing the situation, I see that the system is loaded by PMM agent, it is he who makes the CPU load 100%.

I don't see any errors in the event log, everything works fine.

Is the reason for such a high load from PMM agent that the server has a significant number of databases and it tries to process them in parallel and the only solution is to add a CPU to this server?

### Expected Results

CPU usage less than 20% percent

### Actual Results

CPU usage 100%

### Version

PMM server version: 2.30.0
PMM admin version: 2.30.0
PMM agent version: 2.30.0

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by igor-cherkasov** [comment]
Hello @neverlless

We know that CPU usage in 2.30.0 was quite high. Yesterday we released version 2.31.0, which contains CPU usage improvements, so CPU usage should be decreased by multiple times. Could you please try 2.31.0 and come back with results to see if problem gone?

**Comment by neverlless** [comment]
> Hello @neverlless
> 
> We know that CPU usage in 2.30.0 was quite high. Yesterday we released version 2.31.0, which contains CPU usage improvements, so CPU usage should be decreased by multiple times. Could you please try 2.31.0 and come back with results to see if problem gone?

Hello @igor-cherkasov 

Yes, I already tried 2.31.0.

According to observations for the day, the problem with CPU utilization was 100% solved on version 2.31.0.

**Comment by artemgavrilov** [comment]
Great! Then I'm closing this issue.
