### ISSUE TITLE
Add support for github.com/daixiang0/gci 0.9.0

### ISSUE THREAD

**Issue by BupycHuk** [percona/pmm#1447]
### Description

Checks with upgraded github.com/daixiang0/gci are failing because it changed formatting, so we should update our code or configs of gci to make checks pass.
PR that failing https://github.com/percona/pmm/pull/1439

### Expected Results

Checks pass with new gci

### Actual Results

Checks are failing

### Version

https://github.com/percona/pmm/pull/1439

### Relevant logs

```shell
HEAD detached at pull/1439/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   managed/utils/tests/fuzz.go

no changes added to commit (use "git add" and/or "git commit -a")
diff --git a/managed/utils/tests/fuzz.go b/managed/utils/tests/fuzz.go
index 91dfc26..6c5dc12 100644
--- a/managed/utils/tests/fuzz.go
+++ b/managed/utils/tests/fuzz.go
@@ -15,8 +15,7 @@
 
 package tests
 
-import (
-	// go-fuzz uses SHA1 for non-cryptographic hashing
+import ( // go-fuzz uses SHA1 for non-cryptographic hashing
 	"crypto/sha1" //nolint:gosec
 	"fmt"
 	"os"
```

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by artemgavrilov** [comment]
Problem has gone: https://github.com/percona/pmm/pull/1439
