### ISSUE TITLE
mongo db not showing correct query time, considered in seconds but seems like it should be millis

### ISSUE THREAD

**Issue by cap-pardeepsingh** [percona/pmm#1523]
### Description

We are trying to run query analytics on mongo db. we are using locust to run some load scripts. we are getting min and average response in range of few ms. but pmm shows min as ~1 min and max as ~2.5 hours. I am attaching some snapshots here.
pmm query time average is coming as 1 min 57 sec here. Though it should be around ~120 ms. because on locust this time is around ~170 ms.

![image](https://user-images.githubusercontent.com/38239057/208916877-9e31fda2-3e33-4b17-a633-1f3196828ee2.png)

<img width="1739" alt="image" src="https://user-images.githubusercontent.com/38239057/208917357-95c59a89-83e6-49a1-9491-5f1da2173b2c.png">

I checked this from mongo stats as well. 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/38239057/208927722-2d9e06e2-c861-4793-9c43-fba8b7d76f9e.png">

It seems that these values are in millisecond but these values are being considered as seconds. That is the reason we are seeing such higher values in the UI.

### Expected Results

Query time values are considered in seconds but are in milli seconds. 

### Actual Results

Query time is considered in seconds.

### Version

PMM server 2.30.0

### Steps to reproduce

1. enable DB profiling in mongo db
2. push stats from mongo db query analytics stats from mongo to pmm
3. check the UI min, max, average query time. it comes in minutes and way higher than expected

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by cap-pardeepsingh** [comment]
@JiriCtvrtka  can you pls verify if it's a valid bug?

**Comment by JiriCtvrtka** [comment]
@cap-pardeepsingh Hi. sorry I had holidays until now. Today/tomorrow I will ping you about results.

**Comment by JiriCtvrtka** [comment]
@cap-pardeepsingh Hi, sorry that it taking so much time. It is been verifying by our QAs, but some of them are still out, thats why it takes more than.

**Comment by cap-pardeepsingh** [comment]
@JiriCtvrtka no problem. Just let me know when you have some updates on this. Though I don't write much code in go langauge. But if it is a valid issue, I can give a try to fix it, it should not be a big change I guess.

**Comment by puneet0191** [comment]
@cap-pardeepsingh thank you for bringing this to our notice, would it be possible for you to share your load setup script? so we could try to replicate exact same scenario?

**Comment by JiriCtvrtka** [comment]
@cap-pardeepsingh Thank you, yes holidays were great. About problem. If it will be confirmed ticket will be created. Then in case of top priority (I think this one is important so it should be top priority) it should be quick fix (like convert specific values to another units). Anyway feel free to create PR with fix if you are interested in. That would be great. Its no issue that you dont have much go experiences we can tune it during review.

**Comment by JiriCtvrtka** [comment]
@cap-pardeepsingh Hi. Our QAs just confirmed bug, which you reported. 

Ticket for this bug is:
https://jira.percona.com/browse/PMM-11386

Anyway thank you a lot for discover this.

**Comment by artemgavrilov** [comment]
Thanks @JiriCtvrtka. Following progress will be reflected in the created JIRA ticket.
I'm closing this issue. 

@cap-pardeepsingh thank you for your report!
