### ISSUE TITLE
Enable temporarily disabled linters

### ISSUE THREAD

**Issue by BupycHuk** [percona/pmm#1541]
### Description

In the golangci configuration file, we have a bunch of temporarily [disabled](https://github.com/percona/pmm/blob/main/.golangci.yml#L93-L129) [linters](https://golangci-lint.run/usage/linters/).

### Suggested solution

We want to review those disabled, one by one. Our options are: 
1) either enable the rule and fix potential warning messages or 
2) disable the rule and leave a comment explaining why.

It's not impossible to disable a couple of rules if we realize we don't need them.

### Additional context

list of currently disabled linters that
- [x] bodyclose
- [x] containedctx
- [x] contextcheck
- [x] deadcode
- [x] dupl
- [x] errcheck
- [x] errorlint
- [x] execinquery
- [x] forbidigo
- [x] forcetypeassert
- [x] gocognit
- [x] gocritic
- [x] godot
- [x] godox
- [x] golint
- [x] gosimple
- [x] interfacebloat
- [x] ireturn
- [x] maintidx
- [x] nakedret
- [x] nestif
- [x] nilnil
- [x] nilerr
- [x] nonamedreturns
- [x] noctx
- [x] nosnakecase
- [x] nosprintfhostport
- [x] paralleltest
- [x] prealloc
- [x] predeclared
- [x] revive
- [x] tagliatelle
- [x] thelper
- [x] tparallel
- [x] usestdlibvars
- [x] whitespace

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sajdakabir** [comment]
Hey, @BupycHuk I would love to this issue can you please assign it to me?

**Comment by artemgavrilov** [comment]
Hi @sajdakabir, thank you for your interest! This is cumulative issue, we don't expect fixing all linters at once. Moreover it will be very hard to review. So please open individual PR for every linter fix. If you afraid that someone else will start working on the same linter, you can just add comment here to inform others that you already started (BTW we don't have much activity here).

**Comment by atymchuk** [comment]
@JiriCtvrtka Could you please take care of the `execinquery` rule? It seems to be mostly related to slowlog functionality, which is part of QAN I'd assume.

https://pasteboard.co/QfvSXujpeNQ4.png

**Comment by JiriCtvrtka** [comment]
@atymchuk sure. I will take a look right after priorities for this week.
