### ISSUE TITLE
software "mysqld" is not installed: incompatible service

### ISSUE THREAD

**Issue by umgbhalla** [percona/pmm#1552]
### Description

I have done the setup for [pmm](https://docs.percona.com/percona-monitoring-and-management/get-started/backup/prepare_storage_location.html) and [percona-operator mysql cluster](https://docs.percona.com/percona-operator-for-mysql/pxc/monitoring.html) based on documentation instruction for kubernetes,  i m not sure how to resolve  this issue ...
> software "mysqld" is not installed: incompatible service

https://user-images.githubusercontent.com/67634565/211575375-8340d3c8-8afa-4242-9e71-a90e7afc652c.mp4

### Expected Results

backup to s3 like service

### Actual Results

> [ERROR] software "mysqld" is not installed: incompatible service

### Version

pmm-server V2.32.0 , pmm-client v2.32.0

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by artemgavrilov** [comment]
Hello @umgbhalla , backup feature in PMM doesn't support k8s or other containerized DB installations and targets bare metal servers and VMs. If you are using Percona Operator for MySQL then here is how to perform backups for such installation: https://docs.percona.com/percona-operator-for-mysql/pxc/backups.html
