### ISSUE TITLE
DATA_RETENTION env variable can only be expressed in hours

### ISSUE THREAD

**Issue by dmarav** [percona/pmm#1620]
### Description

I am running pmm-server on Docker, and trying to set the data retention to 90 days. 

When setting the `DATA_RETENTION` variable value to 90 following the documentation [here](https://docs.percona.com/percona-monitoring-and-management/setting-up/server/docker.html#environment-variables),  I get an error stating that 90 is an invalid value. 

I was able to track the error log to these sections in the code:
[Environment variable parsing](https://github.com/percona/pmm/blob/41cec88ebd0944a83866c8efcf661f40b3b9da7d/managed/utils/envvars/parser.go#L118-L121)
[Value checking](https://github.com/percona/pmm/blob/41cec88ebd0944a83866c8efcf661f40b3b9da7d/managed/utils/envvars/parser.go#L223-L230)

The issue is that the `time.ParseDuration function` in the second link accepts a specific format, not just the number. 

If I set the value to 2160h (90 * 24), the container starts with no issues.

Please fix the docs with the right values for the variable.

### Expected Results

The container starts and the retention is set to the configured values.

### Actual Results

The container doesn't start with an error log stating the value is not correct.

### Version

PMM Server v2.32.0 (Docker)

### Steps to reproduce

Set the environtment variable DATA_RETENTION to any numeric value.

### Relevant logs

```shell
ERRO[2023-01-24T07:49:28.358+00:00] Configuration error: environment variable "DATA_RETENTION=90" has invalid duration 90.
```

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by artemgavrilov** [comment]
@dmarav Thank you for your report! Fix in documentation was just merged.
