### ISSUE TITLE
Security Vulnerabilities in the existing latest image

### ISSUE THREAD

**Issue by prabinsh** [percona/pmm#1856]
### Description

There are multiple critical vulnerabilities int the underlying CentOS Image.
How can we update the OS?
[twistlock_images_3_9_23_15_48_54.csv](https://github.com/percona/pmm/files/10936423/twistlock_images_3_9_23_15_48_54.csv)

### Expected Results

Need an easier way to update the underlying OS

### Actual Results

NA

### Version

v2.35

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by denisok** [comment]
Hi @prabinsh ,
https://jira.percona.com/browse/PMM-11669

We are working on that to migrate to EL9 base.

What image do you mean? VM or container image?

Thanks,
Denys

**Comment by prabinsh** [comment]
@denisok 
Thank you. I am looking for the container image to deploy in AWS EKS.

**Comment by prabinsh** [comment]
@denisok do you know when the EL9 base image will be released?

**Comment by denisok** [comment]
no, not yet. Testing is on-going. Stay tuned. CC @dygksy

**Comment by BupycHuk** [comment]
Hello @prabinsh, we migrated to Oracle Linux 9; please check new [PMM 2.38.0](https://docs.percona.com/percona-monitoring-and-management/release-notes/2.38.0.html#important-security-updates)

**Comment by prabinsh** [comment]
Thank you for looking into this. Even with the latest version 2.38.0, there are still a significant number of vulnerabilities found in `go`. Relying solely on Percona for a fix may not be reliable unless the user can rebuild the image themselves to address these vulnerabilities.
