### ISSUE TITLE
Make the `godot` linter rule more restrictive.

### ISSUE THREAD

**Issue by atymchuk** [percona/pmm#2268]
### Description

Ref: #1541 

When [enabling](https://github.com/percona/pmm/pull/2252) the `godot` rule, we have intentionally chosen to set its `period` config [parameter](https://github.com/percona/pmm/pull/2252/files#diff-6179837f7df53a6f05c522b6b7bb566d484d5465d9894fb04910dd08bb40dcc9R32) to `false`, since otherwise the PR would be too heavy to review.

We want to turn it back to `true`, i.e. `period: true` so as to make the linter fail when it encounters the absence of the dot at the end of a comment.

This seems to follow Go's conventions and best practices.

### Suggested solution

1. set the `period: true` in the `.golangci.yml` file
2. fix the linter warnings

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishwas-sharma2480** [comment]
Hi I would like to contribute to this issue

**Comment by artemgavrilov** [comment]
@vishwas-sharma2480  Great! Please go ahead and let us know if you will have any questions

**Comment by vishwas-sharma2480** [comment]
Hi @artemgavrilov  thanks for giving me the opportunity to work on this issue . As per the issue only need to change the period config parameter to true would fix possibly fix the issue ?

**Comment by vishwas-sharma2480** [comment]
Hi @artemgavrilov thanks for giving me the opportunity to work on the issue

**Comment by artemgavrilov** [comment]
Hi @vishwas-sharma2480 , we always keeping such issues unassigned, so everyone can contribute. Just send PR once it will be ready and we will link it to this issue.

**Comment by vishwas-sharma2480** [comment]
@artemgavrilov is there any documentation regarding these linter rules i am

**Comment by artemgavrilov** [comment]
@vishwas-sharma2480  you can find this linter config doc here: https://golangci-lint.run/usage/linters/#godot

But issue description already provides all information that needed.

**Comment by vishwas-sharma2480** [comment]
hi @artemgavrilov  i am currently working on this issue made almost 64 commits but its is taking too much time with command
golangci-lint run to see 3 godot warnings at a time is there a command which helps see all the godot warnings

**Comment by artemgavrilov** [comment]
Hi @vishwas-sharma2480 , according to `golangci-lint` documentation you can configure this with `max-issues-per-linter` parameter: https://golangci-lint.run/usage/configuration/#issues-configuration

Also may be helpful: https://stackoverflow.com/questions/67411661/how-to-make-goclangci-lint-show-all-errors-at-once
