### ISSUE TITLE
SSH Tunnelling

### ISSUE THREAD

**Issue by NaTorOG** [percona/pmm#2282]
### Description

Hello, I was looking at Percona Server for MySQL 8.0 and Percona Monitoring and Management.

I was wondering if an architecture like this is possible.

SERVER A 
- Contains Podman instance of Percona Server running on localhost   

COMPUTER B
- Connected to server A with SSH and binding a port for SSH Tunnell to 3306 of Server A 
- Running Percona Monitoring Server and Client on Podman Desktop

Purpose, connecting from my computer to web page to monitor the percona server on SERVER A

I was looking at https://docs.percona.com/percona-monitoring-and-management/ but I have not found something that can be interesting about SSH tunnells

### Suggested solution

Adding to https://docs.percona.com/percona-monitoring-and-management/ and eventual situation with SSH Tunnelling or expand the details for remote monitoring

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BupycHuk** [comment]
Hi @NaTorOG could you please ask this question in our forum, please? https://forums.percona.com/c/percona-monitoring-and-management-pmm/percona-monitoring-and-management-pmm-v2/31
