### ISSUE TITLE
Enable `errcheck` linter rule

### ISSUE THREAD

**Issue by ademidoff** [percona/pmm#2346]
### Description

Ref: #1541
We'd like to enable `errcheck` [linter rule](https://github.com/kisielk/errcheck).

### Suggested solution

- evaluate if we can afford to enable the rule
- if yes, fix all linter error to make tests pass
- if not, disable the rule and leave a comment explaining why (subject to review by the dev team)

### Additional context

The rule can be enabled by simply removing [this line](https://github.com/percona/pmm/blob/26895fa270fb28db2dd985228ebfd714eca2c70f/.golangci.yml#L117). 
You can check similar PRs to see how we enabled some other rules (ref: #1541)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishwas-sharma2480** [comment]
Hi @atymchuk I would like to work on this issue but i have doubt how do I know that we can afford to enable this linter for example i get linter warning like below
admin/pkg/client/tarball/tarball.go:151:22: Error return value of res.Body.Close is not checked (errcheck)        defer res.Body.Close() //nolint:gosec

**Comment by vishwas-sharma2480** [comment]
hi @atymchuk and @artemgavrilov  any update on above ?

**Comment by artemgavrilov** [comment]
Hi @vishwas-sharma2480 , in your particular example I think it makes sense to mute warning with `nolint` option. But in general every case should be reviewed independently.

**Comment by vishwas-sharma2480** [comment]
Hi @artemgavrilov I have raised another PR can you and team please review it ?
