### ISSUE TITLE
Migrate mockery configuration from flags to config file

### ISSUE THREAD

**Issue by BupycHuk** [percona/pmm#2527]
### What should be done:
Mockery marked `go:generate` with flags approach as deprecated. Instead they introduced package level config file. We need to migrate to it.

### Details:
https://vektra.github.io/mockery/v2.31/migrating_to_packages/
https://vektra.github.io/mockery/v2.31/configuration/

```
10 Jul 23 10:58 EET WRN DEPRECATION: use of the packages config will be the only way to generate mocks in v3. Please migrate your config to use the packages feature. dry-run=false migration=https://vektra.github.io/mockery/v2.31/migrating_to_packages/ url=https://vektra.github.io/mockery/v2.31/features/#packages-configuration version=v2.31.1 
```

### Benefit:
Mockery V3 won't support `go:generate` directives anymore, so we need to be prepared for it.

### Suggested implementation:
implement migration process described in https://vektra.github.io/mockery/v2.31/migrating_to_packages/ 

### Jira task number:
https://jira.percona.com/browse/PMM-12302

**Comment by ademidoff** [comment]
@BupycHuk Shall we close it (PTAL this [discussion](https://perconadev.atlassian.net/browse/PMM-12302?focusedCommentId=409282))
