### ISSUE TITLE
Update lib/pq library

### ISSUE THREAD

**Issue by BupycHuk** [percona/pmm#2528]
### Description

We can't bump version of pg to 1.10.7 https://github.com/percona/pmm/pull/1360 now, because its breaking PMM. PG SSL connection doesnt work then. Please see description in: https://jira.percona.com/browse/PMM-10927.
Upgrade of lib/pq made library added verification of DNSName by default

Related issue: https://github.com/lib/pq/issues/1106 

Possible solution:
Latest version has fix for this problem: https://github.com/lib/pq/releases/tag/v1.10.9
add `sslsni=0` to postgres DSN****

### Expected Results

PMM can connect to the server with SSL enabled and QAN data are collected

### Actual Results

QAN data are not being collected

- [X] I agree to follow Percona Community Code of Conduct

**Comment by rishavmehra** [comment]
![image](https://github.com/percona/pmm/assets/68805388/9f4e229d-4c10-4460-bcf7-c97ff8ed6a92)
@BupycHuk 
I want to this jira issue But I dont have permissions.

My username: rishavmehra

**Comment by BupycHuk** [comment]
Hi @rishavmehra, I've fixed the problem with Jira
