### ISSUE TITLE
[Maintenance] Fix linter issues in the repo

### ISSUE THREAD

**Issue by BupycHuk** [percona/pmm#2538]
* What should be done:
Address linters comments if possible or add `//nolint:` comment in case it's hard to fix.

* Benefit:
At the moment we have failing linters in pmm repo https://github.com/percona/pmm/actions/runs/6469234262, we need to fix them to not see in each PR.

* Suggested implementation:

* Details:

**Comment by u5surf** [comment]
@BupycHuk Hi! I would like to work on this issue.

**Comment by BupycHuk** [comment]
@u5surf Yes, let's comment nolint
