### ISSUE TITLE
pmm2-client ubuntu14.04

### ISSUE THREAD

**Issue by willianflasky** [percona/pmm#2742]
### Description

Does pmm2-client support ubuntu 14.04、16.04 please?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by willianflasky** [comment]
if support it, please list docs or solution idea. thanks a lot.

**Comment by BupycHuk** [comment]
Hi, we don't support these versions and we don't have packages for these distributions, but you can try to use our tarballs from our [downloads page](https://www.percona.com/downloads).
Thank you
