### ISSUE TITLE
Missing MySQL / MongoDB in PMM menu on the left v2.41.2

### ISSUE THREAD

**Issue by GenLN** [percona/pmm#2922]
### Description

Installed PMM 2.41.2, now i don't see MySQL and MongoDB on the left PMM menu
![image](https://github.com/percona/pmm/assets/26070480/a54702f1-ed4f-4942-a4a5-da1ca6b646cc)

### Expected Results

To see these items on the left Menu

### Actual Results

Missing

### Version

PMM Server 2.41.2

### Steps to reproduce

Install PMM 2.41.2

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by puneet0191** [comment]
hey @GenLN are you monitoring any Mysql/MongoDb instances with PMM? 

I just checked 2.41.2 for my test instance, I was monitoring a MySQL service, hence I am able to see the MySQL menu option

![image](https://github.com/percona/pmm/assets/3048593/001cb2a0-1454-421c-8ecc-a6297db7862e)

**Comment by GenLN** [comment]
Yes a lot of them. So as I checked again, now it shows it... perhaps it needs some time for agents to get reconnected to pmm server or pmm server to refresh metrics?

I can close this if you wish

**Comment by puneet0191** [comment]
yes please, that could be the case, thanks a lot for your issue
