### ISSUE TITLE
VMAGENT_ env vars not forwarded to vmagent (to enable TCP6)

### ISSUE THREAD

**Issue by ChristophWurst** [percona/pmm#3013]
### Description

I want to use pmm-agent on a IPv6-only host. vmagent supports IPv6 but it has to be turned through `-enableTCP6` or the environment variable ENABLETCP6.
For pmm-agent I want to set VMAGENT_ENABLETCP6.

### Expected Results

pmm-agent should be able to forward env vars with a prefix: https://github.com/percona/pmm/commit/ffc66f09b0af07e8f41ef52b9e1b4618453438a1#diff-2d22b4ddd67626775c4f9f26b9a02431d5d3bb1a5c13428822520f894a996b09R71-R75, but this mechanism does not seem to work.

### Actual Results

Despite starting pmm-agent with environment variables VMAGENT_* the process of vmagent does *not* have supplied environment variables. It only has the variables VMAGENT_remoteWrite_basicAuth_password and VMAGENT_remoteWrite_basicAuth_username.

The debug logs confirm that the agent does not forward the environment variables:

```
time="2024-06-04T10:13:08.414+02:00" level=debug msg="Starting: /usr/local/percona/pmm2/exporters/vmagent -envflag.enable=true -envflag.prefix=VMAGENT_ -httpListenAddr=127.0.0.1:42000 -loggerLevel=INFO -promscrape.config=/usr/local/percona/pmm2/tmp/vm_agent/agent_id/a-863d-b-c-d/vmagentscrapecfg -promscrape.maxScrapeSize=64MiB -remoteWrite.maxDiskUsagePerURL=1073741824 -remoteWrite.tlsInsecureSkipVerify=true -remoteWrite.tmpDataPath=/usr/local/percona/pmm2/tmp/vmagent-temp-dir -remoteWrite.url=https://172.19.0.1:3000/victoriametrics/api/v1/write (environment: VMAGENT_remoteWrite_basicAuth_password=abc==, VMAGENT_remoteWrite_basicAuth_username=api_key)." agentID=/agent_id/a-b-c-d component=agent-process type=vm_agent
```

### Version

pmm-agent v2.41.2

### Steps to reproduce

1) Install the pmm-client
2) Run pmm-agent manually and set environment variables or adjust systemd service files with the custom env vars
3) cat /proc/$(pidof vmagent)/environ

### Relevant logs

```Shell
time="2024-06-04T10:13:08.414+02:00" level=debug msg="Starting: /usr/local/percona/pmm2/exporters/vmagent -envflag.enable=true -envflag.prefix=VMAGENT_ -httpListenAddr=127.0.0.1:42000 -loggerLevel=INFO -promscrape.config=/usr/local/percona/pmm2/tmp/vm_agent/agent_id/a-863d-b-c-d/vmagentscrapecfg -promscrape.maxScrapeSize=64MiB -remoteWrite.maxDiskUsagePerURL=1073741824 -remoteWrite.tlsInsecureSkipVerify=true -remoteWrite.tmpDataPath=/usr/local/percona/pmm2/tmp/vmagent-temp-dir -remoteWrite.url=https://172.19.0.1:3000/victoriametrics/api/v1/write (environment: VMAGENT_remoteWrite_basicAuth_password=abc==, VMAGENT_remoteWrite_basicAuth_username=api_key)." agentID=/agent_id/a-b-c-d component=agent-process type=vm_agent
```

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by ChristophWurst** [comment]
Forum post with more information about the setup and why ipv6 is needed for vmagent: https://forums.percona.com/t/unable-to-connect-ipv6-host-to-dual-stacked-pmm-host/30632

**Comment by BupycHuk** [comment]
Hello @ChristophWurst, VMAGENT_ flag should be passed to PMM Server container to forward it to vmagent.

**Comment by ChristophWurst** [comment]
@BupycHuk I must have misunderstood the feature then. Does this mean that only the vmagent of the PMM host can be configured for IPv6? Is there any other way to pass environment variables to the vmagent started by pmm-agent on a monitored node?

**Comment by BupycHuk** [comment]
No, once you passed the variable to PMM Server it will be forwarded to all PMM Clients.

**Comment by ChristophWurst** [comment]
Got it! Thanks a lot!
