### ISSUE TITLE
pt-archiver error

### ISSUE THREAD

**Issue by runshark** [percona/pmm#3327]
### Description

The tables in MySQL are UTF8, and there are special characters in the tables. When using pt-archiver to add the parameter “-- charset UTF8” to export a local file, an error will be reported as follows. If “-- charset UTF8” is removed, the exported file will be garbled again。What should I do?

error message：pt-archiver  Unicode surrogate U+D83D is illegal in UTF-8 at /usr/bin/pt-archiver line 6951.
![Uploading 17320973799871.png…]()

### Expected Results

error message：pt-archiver  Unicode surrogate U+D83D is illegal in UTF-8 at /usr/bin/pt-archiver line 6951.

### Actual Results

error message：pt-archiver  Unicode surrogate U+D83D is illegal in UTF-8 at /usr/bin/pt-archiver line 6951.

### Version

pt-archiver 3.6.0

### Code of Conduct

- [X] I agree to follow Percona Community Code of Conduct

**Comment by BupycHuk** [comment]
Hi @runshark, PT archiver isn't used in PMM. Please create Jira task in https://jira.percona.com/browse/PT.
